import type { TeamIdentity } from "./teamAccess"

export const defaultClubTeams: TeamIdentity[] = [
  {
    id: "u7-mixed",
    name: "U7 Mixed",
    ageGroup: "U7",
    section: "mixed",
    squadName: "",
    displayName: "U7 Mixed",
    primaryColour: "#0ea5e9",
    secondaryColour: "#ffffff",
  },
  {
    id: "u8-boys-sharks",
    name: "U8 Boys Sharks",
    ageGroup: "U8",
    section: "boys",
    squadName: "Sharks",
    displayName: "U8 Boys Sharks",
    primaryColour: "#0ea5e9",
    secondaryColour: "#ffffff",
  },
  {
    id: "u8-girls-lionesses",
    name: "U8 Girls Lionesses",
    ageGroup: "U8",
    section: "girls",
    squadName: "Lionesses",
    displayName: "U8 Girls Lionesses",
    primaryColour: "#7c3aed",
    secondaryColour: "#ffffff",
  },
  {
    id: "u9-boys-sharks",
    name: "U9 Boys Sharks",
    ageGroup: "U9",
    section: "boys",
    squadName: "Sharks",
    displayName: "U9 Boys Sharks",
    primaryColour: "#0ea5e9",
    secondaryColour: "#ffffff",
  },
  {
    id: "u9-boys-lions",
    name: "U9 Boys Lions",
    ageGroup: "U9",
    section: "boys",
    squadName: "Lions",
    displayName: "U9 Boys Lions",
    primaryColour: "#f59e0b",
    secondaryColour: "#ffffff",
  },
  {
    id: "u10-girls-sharks",
    name: "U10 Girls Sharks",
    ageGroup: "U10",
    section: "girls",
    squadName: "Sharks",
    displayName: "U10 Girls Sharks",
    primaryColour: "#0ea5e9",
    secondaryColour: "#ffffff",
  },
  {
    id: "u11-girls-lionesses",
    name: "U11 Girls Lionesses",
    ageGroup: "U11",
    section: "girls",
    squadName: "Lionesses",
    displayName: "U11 Girls Lionesses",
    primaryColour: "#7c3aed",
    secondaryColour: "#ffffff",
  },
  {
    id: "u16-boys-lions",
    name: "U16 Boys Lions",
    ageGroup: "U16",
    section: "boys",
    squadName: "Lions",
    displayName: "U16 Boys Lions",
    primaryColour: "#f59e0b",
    secondaryColour: "#ffffff",
  },
  {
    id: "u16-boys-sharks",
    name: "U16 Boys Sharks",
    ageGroup: "U16",
    section: "boys",
    squadName: "Sharks",
    displayName: "U16 Boys Sharks",
    primaryColour: "#0ea5e9",
    secondaryColour: "#ffffff",
  },
  {
    id: "u16-girls-lionesses",
    name: "U16 Girls Lionesses",
    ageGroup: "U16",
    section: "girls",
    squadName: "Lionesses",
    displayName: "U16 Girls Lionesses",
    primaryColour: "#7c3aed",
    secondaryColour: "#ffffff",
  },
]
