"use client"

import { useEffect,useState } from "react"
import MatchCentreWorkflow from "./MatchCentreWorkflow"
import MatchdayStatsBridge from "./MatchdayStatsBridge"
import TacticalBoardWorkspace from "./TacticalBoardWorkspace"
import "./matchday-premium.css"

type Workspace="match"|"tactics"|"report"
type SavedMatchSummary={seconds:number;home:number;away:number;activePeriod:number}
const workspaceStorageKey="football-os-matchday-workspace-v1",matchStateStorageKey="football-os-matchday-state-v4"
const workspaces=[{id:"match" as Workspace,label:"Match Centre",shortLabel:"Match",description:"Setup, squad, editable starting lineup, planner and live match control.",icon:"◉"},{id:"tactics" as Workspace,label:"Tactical Board",shortLabel:"Tactics",description:"Move the live lineup, shape the team and save formations.",icon:"◇"},{id:"report" as Workspace,label:"Match Report",shortLabel:"Report",description:"Player events, statistics, opposition and full-time summary.",icon:"▤"}]
function formatClock(seconds:number){const safe=Math.max(0,Math.floor(seconds||0));return `${Math.floor(safe/60)}:${String(safe%60).padStart(2,"0")}`}
function readSavedMatch():SavedMatchSummary|null{try{const raw=window.localStorage.getItem(matchStateStorageKey);if(!raw)return null;const value=JSON.parse(raw) as Partial<SavedMatchSummary>,summary={seconds:Number(value.seconds??0),home:Number(value.home??0),away:Number(value.away??0),activePeriod:Number(value.activePeriod??0)};if(!summary.seconds&&!summary.home&&!summary.away)return null;return summary}catch{return null}}
export default function MatchdayScreen(){const [workspace,setWorkspace]=useState<Workspace>("match"),[savedMatch,setSavedMatch]=useState<SavedMatchSummary|null>(null),active=workspaces.find(i=>i.id===workspace)??workspaces[0];useEffect(()=>{try{const saved=window.localStorage.getItem(workspaceStorageKey) as Workspace|null;if(saved&&workspaces.some(i=>i.id===saved))setWorkspace(saved)}catch{}const refresh=()=>setSavedMatch(readSavedMatch());refresh();window.addEventListener("storage",refresh);window.addEventListener("focus",refresh);const timer=window.setInterval(refresh,2000);return()=>{window.removeEventListener("storage",refresh);window.removeEventListener("focus",refresh);window.clearInterval(timer)}},[]);function selectWorkspace(next:Workspace){setWorkspace(next);try{window.localStorage.setItem(workspaceStorageKey,next)}catch{}window.scrollTo({top:0,behavior:"smooth"})}return <div className="matchday-premium-shell" style={shell}><section style={hero}><div style={{minWidth:0}}><div style={eyebrow}>MATCHDAY</div><h1 style={title}>{active.label}</h1><p style={copy}>{active.description}</p>{savedMatch&&<button type="button" onClick={()=>selectWorkspace("match")} style={resume}><span style={pulse}/><span><small style={resumeLabel}>MATCH IN PROGRESS · P{savedMatch.activePeriod+1}</small><strong style={score}>{savedMatch.home}–{savedMatch.away}</strong><span style={clock}>{formatClock(savedMatch.seconds)} · Resume</span></span><b>→</b></button>}</div><div style={badge}>{active.icon}</div></section><nav aria-label="Matchday workspaces" style={nav}>{workspaces.map(item=><button key={item.id} type="button" aria-pressed={workspace===item.id} onClick={()=>selectWorkspace(item.id)} style={workspace===item.id?navActive:navButton}><span>{item.icon}</span><strong>{item.shortLabel}</strong></button>)}</nav><main>{workspace==="match"&&<MatchCentreWorkflow/>}{workspace==="tactics"&&<TacticalBoardWorkspace/>}{workspace==="report"&&<MatchdayStatsBridge/>}</main></div>}
const shell={display:"grid",gap:12,paddingBottom:112},hero={borderRadius:24,padding:17,background:"rgba(13,24,41,.94)",border:"1px solid #1f3048",display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:14,color:"white"},eyebrow={fontSize:10,fontWeight:950,letterSpacing:1.1,color:"#93c5fd"},title={margin:"5px 0 0",fontSize:28,letterSpacing:-1},copy={margin:"6px 0 0",maxWidth:560,color:"#94a3b8",fontWeight:700,lineHeight:1.4},badge={width:48,height:48,flex:"0 0 48px",borderRadius:15,display:"grid",placeItems:"center",background:"#2563eb",fontSize:22,fontWeight:950},resume={width:"min(100%,420px)",marginTop:12,display:"grid",gridTemplateColumns:"9px minmax(0,1fr) auto",gap:9,alignItems:"center",border:"1px solid rgba(74,222,128,.2)",borderRadius:15,padding:10,color:"white",background:"rgba(22,101,52,.16)",textAlign:"left" as const},pulse={width:8,height:8,borderRadius:999,background:"#4ade80"},resumeLabel={display:"block",color:"#86efac",fontSize:9,fontWeight:950},score={display:"inline-block",marginTop:2,marginRight:8,fontSize:18},clock={color:"#94a3b8",fontSize:11},nav={position:"sticky" as const,top:70,zIndex:30,display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:5,padding:5,borderRadius:17,background:"rgba(7,16,31,.94)",border:"1px solid #1f3048",backdropFilter:"blur(18px)"},navButton={minHeight:46,border:0,borderRadius:12,background:"transparent",color:"#718096",display:"flex",alignItems:"center",justifyContent:"center",gap:6,fontWeight:850},navActive={...navButton,background:"#16243a",color:"white"}
